server:
  port: 9002
  
spring:
  application:
    name: EurekaClientProducer
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      fetch-registry: true
      register-with-eureka: true
