server:
  port: 8002
  
spring:
  application:
    name: EurekaClientFeignConsumer
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      fetch-registry: true
      register-with-eureka: true
