server:
  port: 1000
  
spring:
  application:
    name: SpringCloudUserService
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      fetch-registry: true
      register-with-eureka: true
