server:
  port: 1001
  
spring:
  application:
    name: SpringCloudEmployeeService
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      fetch-registry: true
      register-with-eureka: true
